### ISSUE TITLE
BWA module memory

### ISSUE THREAD

**Issue by arontommi** [ewels/clusterflow#112]
Hi, 

I am running into issues with allocated memory of bwa.cfmod.pl. it seems that the 5G that the module allocates for the sbatch job are not enough and the job gets canceled. Is there a way to manually override Module requirements ?

**Comment by arontommi** [comment]
Nevermind, fixed with @custom_job_submit_command

**Comment by ewels** [comment]
Hi @arontommi,

Sorry that you were running into problems here - what was a more appropriate amount of memory? I'd prefer to change this in the module so that other users don't run into the same problem.

Thanks,

Phil

**Comment by arontommi** [comment]
Hi! 

I ran it with 8G. I guess that might have been a little over the top as the typical requirement is about 5,5 Gfor short reads (https://sourceforge.net/p/bio-bwa/mailman/message/32268544 ) 

I guess setting the module to 6G would be enough?

**Comment by ewels** [comment]
Great stuff, many thanks. I'd prefer to be cautious with this (I know how annoying memory failures are) and 8G still isn't loads, so I'll probably bump it to that.

**Comment by arontommi** [comment]
Fantastic. Thanks for a great tool.
